//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahoa
    {
        public string IDMH { get; set; }
        public string Text { get; set; }
        public string KeyP { get; set; }
        public string KeyA { get; set; }
        public string KeyG { get; set; }
        public string TextMH { get; set; }
        public string IDAccount { get; set; }
    
        public virtual User User { get; set; }
    }
}
